In [2]:
import pandas as pd
import numpy as np

# index ,by default we have integer index
sales = [10,20,30,40]
ser = pd.Series(sales,name = 'sales')
ser

0    10
1    20
2    30
3    40
Name: sales, dtype: int64

In [15]:
# custom index
items  = [10,20,30,40]
ser = pd.Series(sales,index = items) #while creating series specify index
print(ser)
print('*' *  30)
ser.index = ['a','b','c','d'] # assign index later
print(ser)
print('*' *  30)
print(ser['b' : 'd']) #outer limit is inclusive when working with custom index (label based index)

#Note if working with custom integer index always use loc or iloc as without it pandas is confused whether to use label slicing or positional slicing and might return []

10    10
20    20
30    30
40    40
dtype: int64
******************************
a    10
b    20
c    30
d    40
dtype: int64
******************************
b    20
c    30
d    40
dtype: int64

In [28]:
# iloc / loc [row,cols]
series = pd.Series(np.arange(1,6),index = ['a','b','c','d','e'])
# position based indexing ,uses row number
print(series.iloc[1]) #single row
print(f'multi ---- {series.iloc[[1,4]]}') #multiple row
print(f'range ------ {series.iloc[0:2]}') #range of rows
print('*' *  30)
# label based indexing,uses index label and the values are inclusive
print(series.loc['b'])
print(series.loc[['b','e']])
print(series.loc['b':'d'])

2
multi ---- b    2
e    5
dtype: int64
range ------ a    1
b    2
dtype: int64
******************************
2
b    2
e    5
dtype: int64
b    2
c    3
d    4
dtype: int64

In [41]:
# reset_index
series = series.loc[series != 2] #in this case it has drop index which had value 2 i.e index b
print(series)
print('*' *  30)
# reset to default int index and store the previous index as a new column
print(f'old index stored -- {series.reset_index()}')

# use drop = True if we dont want to store the previous index value
series.reset_index(drop = True)

a    1
c    3
d    4
e    5
dtype: int64
******************************
old index stored --   index  0
0     a  1
1     c  3
2     d  4
3     e  5

0    1
1    3
2    4
3    5
dtype: int64

In [45]:
#duplicate value in index, in this case if we use loc it will fetch all the corresponding rows
sales = [0,5,15,100,515]
item = ['a','b','c','d','c']

series  = pd.Series(sales,item)
print(series.loc['c'])

# check if index is unique
print(series.index.is_unique)

#get duplicated index values
print(series.index.duplicated())

c     15
c    515
dtype: int64
False
[False False False False  True]