In [1]:
import pandas as pd

# Creating a dataframe

# 1) From python dict
dict_df = pd.DataFrame({"id":[1,2],
                        "num":[1,2],
                        "family":['Ambani','Adani']})
dict_df

   id  num  family
0   1    1  Ambani
1   2    2   Adani

In [2]:
# 2) Create df by reading a csv
oil_df = pd.read_csv('/content/sample_data/real-oil-price.csv')
oil_df

           date  wti_nominal  cpi_index    wti_real
0    1986-01-01        18.95    109.900   56.952251
1    1986-02-01        13.23    109.700   39.833878
2    1986-03-01        10.25    109.100   31.031194
3    1986-04-01        13.38    108.700   40.656121
4    1986-05-01        14.30    109.000   43.332017
..          ...          ...        ...         ...
477  2025-11-01        58.58    325.063   59.522505
478  2025-12-01        57.26    326.031   58.008524
479  2026-01-01        64.50    326.588   65.231725
480  2026-02-01        66.96    327.460   67.539300
481  2026-03-01       102.86    330.293  102.860000

[482 rows x 4 columns]

In [ ]:
# properties
print(f'shape----{oil_df.shape}')
print('-'* 30)
print(f'index----{oil_df.index}') #row index
print('-'* 30)
print(f'column----{oil_df.columns}')
print('-'* 30)
print(f'axes----{oil_df.axes}')
print('-'* 30)
print(f'dtypes----{oil_df.dtypes}')
print('-'* 30)

shape----(482, 4)
------------------------------
index----RangeIndex(start=0, stop=482, step=1)
------------------------------
column----Index(['date', 'wti_nominal', 'cpi_index', 'wti_real'], dtype='object')
------------------------------
axes----[RangeIndex(start=0, stop=482, step=1), Index(['date', 'wti_nominal', 'cpi_index', 'wti_real'], dtype='object')]
------------------------------
dtypes----date            object
wti_nominal    float64
cpi_index      float64
wti_real       float64
dtype: object
------------------------------

In [ ]:
# it shows non-null count if data is less than 1.7million rows
print(oil_df.info())
print('-'*30)
# it shows null count as well
print(oil_df.info(show_counts = True))

print('-'*30)
# gives statistic only for numeric data
print(oil_df.describe())
print('-'*30)
# gives statistic only for all data
print(oil_df.describe(include = 'all'))
print('-'*30)
#only specific data type
print(oil_df.describe(include = 'object'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482 entries, 0 to 481
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         482 non-null    object
 1   wti_nominal  482 non-null    float64
 2   cpi_index    482 non-null    float64
 3   wti_real     482 non-null    float64
dtypes: float64(3), object(1)
memory usage: 15.2+ KB
None
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482 entries, 0 to 481
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         482 non-null    object
 1   wti_nominal  482 non-null    float64
 2   cpi_index    482 non-null    float64
 3   wti_real     482 non-null    float64
dtypes: float64(3), object(1)
memory usage: 15.2+ KB
None
------------------------------
       wti_nominal   cpi_index    wti_real
count   482.000000  482.000000  482.000000
mean     48.380228  201.407359   74.640530
std      29.538380   57.131096   35.252929
min      10.250000  108.700000   22.885018
25%      20.342500  154.775000   48.124645
50%      44.375000  199.350000   64.166276
75%      71.230000  238.033750   95.341534
max     139.960000  330.293000  212.577810
------------------------------
              date
count          482
unique         482
top     2026-03-01
freq             1

In [13]:
# Accessing dataframe
# 1) using [] ,this is useful if col name has space or special character
print(f'oil --- {oil_df['cpi_index']}')
print('-' * 30)
print(f'oil multi col --- {oil_df[['cpi_index','wti_nominal']]}')

#using dot notation
print(f'oil dot --- {oil_df.cpi_index}')

oil --- 0      109.900
1      109.700
2      109.100
3      108.700
4      109.000
        ...
477    325.063
478    326.031
479    326.588
480    327.460
481    330.293
Name: cpi_index, Length: 482, dtype: float64
------------------------------
oil multi col ---      cpi_index  wti_nominal
0      109.900        18.95
1      109.700        13.23
2      109.100        10.25
3      108.700        13.38
4      109.000        14.30
..         ...          ...
477    325.063        58.58
478    326.031        57.26
479    326.588        64.50
480    327.460        66.96
481    330.293       102.86

[482 rows x 2 columns]
oil dot --- 0      109.900
1      109.700
2      109.100
3      108.700
4      109.000
        ...
477    325.063
478    326.031
479    326.588
480    327.460
481    330.293
Name: cpi_index, Length: 482, dtype: float64

In [ ]:
# apply lets you apply custom function to panda series
s = pd.Series([10, 20, 30, 40])

result = s.apply(lambda x: x * 2)
print(result)
print('*' * 30)

# where(condition,value if false , inplace = True/False)
result = s.where(s > 20, -1)
print(result)
print('*' * 30)

#mask(condition,value if true)
result = s.mask(s > 20, -1)
print(result)
print('*' * 30)

0    20
1    40
2    60
3    80
dtype: int64
******************************
0    -1
1    -1
2    30
3    40
dtype: int64
******************************
0    10
1    20
2    -1
3    -1
dtype: int64
******************************

In [ ]:
# map If value not present in dictionary → it becomes NaN,Works only on Series
s = pd.Series(['A','B','C','A'])

mapping = {
    'A': 'Apple',
    'B': 'Banana',
    'C': 'Cherry'
}

print(s.map(mapping))

s = pd.Series([10,20,30])
# using function
print(s.map(lambda x: x * 2))

0     Apple
1    Banana
2    Cherry
3     Apple
dtype: object
0    20
1    40
2    60
dtype: int64

In [10]:
# working with duplicates
import pandas as pd

df = pd.DataFrame({
    'Name': ['A', 'B', 'A', 'C', 'B'],
    'Age': [20, 25, 20, 30, 25]
})

print(df)
print('-'*30)
print(df.duplicated())
print('-'*30)
print(df.duplicated(subset='Name'))
print('-'*30)
print(df.duplicated(subset=['Name', 'Age']))
print('-'*30)
df.duplicated(keep='last') #Last occurrence = False Earlier ones = True ,first is other value
print('-'*30)
df.duplicated(keep=False) #all duplicates are true,else false
print('-'*30)
df.drop_duplicates(subset='Name')

  Name  Age
0    A   20
1    B   25
2    A   20
3    C   30
4    B   25
------------------------------
0    False
1    False
2     True
3    False
4     True
dtype: bool
------------------------------
0    False
1    False
2     True
3    False
4     True
dtype: bool
------------------------------
0    False
1    False
2     True
3    False
4     True
dtype: bool
------------------------------
------------------------------
------------------------------

  Name  Age
0    A   20
1    B   25
3    C   30