In [2]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR', 'Finance'],
    'Employee': ['A', 'B', 'C', 'D', 'E'],
    'Salary': [50000, 40000, 60000, 45000, 70000]
})

print(df)

  Department Employee  Salary
0         IT        A   50000
1         HR        B   40000
2         IT        C   60000
3         HR        D   45000
4    Finance        E   70000

In [8]:
#Groupby single column
print(df.groupby('Department')['Salary'].mean())
print('-' * 30)

# group by multi column,this creates index for each column
print(df.groupby(['Department', 'Employee'])['Salary'].sum())
print('-' * 30)

# group by multi column,this does not creates index for each column
print(df.groupby(['Department', 'Employee'],as_index = False)['Salary'].sum())
print('-' * 30)

# multiple aggregations
print(df.groupby('Department')['Salary'].agg(['sum','mean']))
print('-'*30)

print(df.groupby('Department')['Salary'].mean().reset_index())
print('-'*30)

# Group entire Df
print(df.groupby('Department').sum(numeric_only=True))
print('-'*30)

# custom function
print(df.groupby('Department')['Salary'].apply(lambda x: x.max() - x.min()))
print('-'*30)

Department
Finance    70000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64
------------------------------
Department  Employee
Finance     E           70000
HR          B           40000
            D           45000
IT          A           50000
            C           60000
Name: Salary, dtype: int64
------------------------------
  Department Employee  Salary
0    Finance        E   70000
1         HR        B   40000
2         HR        D   45000
3         IT        A   50000
4         IT        C   60000
------------------------------
               sum     mean
Department
Finance      70000  70000.0
HR           85000  42500.0
IT          110000  55000.0
------------------------------
  Department   Salary
0    Finance  70000.0
1         HR  42500.0
2         IT  55000.0
------------------------------
            Salary
Department
Finance      70000
HR           85000
IT          110000
------------------------------
Department
Finance        0
HR          5000
IT         10000
Name: Salary, dtype: int64
------------------------------

In [14]:
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR'],
    'Year': [2023, 2024, 2023, 2024],
    'Salary': [50000, 60000, 40000, 45000]
})

# multilevel index Level 0 → Department Level 1 → Year
grouped = df.groupby(['Department', 'Year'])['Salary'].sum()
print(grouped)

# 1) Swaplevel  Level 1 → Department Level 0 → Year
print('-' * 30)
print(grouped.swaplevel())
# grouped.swaplevel(0, 1)

# drop level
print('-' * 30)
grouped.droplevel('Year')

Department  Year
HR          2023    40000
            2024    45000
IT          2023    50000
            2024    60000
Name: Salary, dtype: int64
------------------------------
Year  Department
2023  HR            40000
2024  HR            45000
2023  IT            50000
2024  IT            60000
Name: Salary, dtype: int64
------------------------------

Department
HR    40000
HR    45000
IT    50000
IT    60000
Name: Salary, dtype: int64

In [21]:
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR'],
    'Salary': [50000, 60000, 40000, 45000],
    'Bonus': [5000, 7000, 3000, 3500]
})

# agg demo
print(df.groupby('Department').agg({
    'Salary': 'mean',
    'Bonus': 'sum'
}))
print('-' * 30)

# multi func per col
print(df.groupby('Department').agg({
    'Salary': ['mean', 'max'],
    'Bonus': ['sum', 'min']
}))
print('-' * 30)

# named agg
print(df.groupby('Department').agg(
    Avg_Salary = ('Salary', 'mean'),
    Total_Bonus = ('Bonus', 'sum')
))
print('-' * 30)

# custom func
df.groupby('Department')['Salary'].agg(
    lambda x: x.max() - x.min()
)

             Salary  Bonus
Department
HR          42500.0   6500
IT          55000.0  12000
------------------------------
             Salary         Bonus
               mean    max    sum   min
Department
HR          42500.0  45000   6500  3000
IT          55000.0  60000  12000  5000
------------------------------
            Avg_Salary  Total_Bonus
Department
HR             42500.0         6500
IT             55000.0        12000
------------------------------

Department
HR     5000
IT    10000
Name: Salary, dtype: int64

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Sales"],
    "Employee": ["A", "B", "C", "D", "E"],
    "Salary": [50000, 60000, 40000, 45000, 70000]
})

print(df)
print('-' * 30)
print(df.groupby("Department")["Salary"].mean())
print('-' * 30)
# Transform works with groupby and helps keep the same number of row
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")

print(df)

  Department Employee  Salary
0         IT        A   50000
1         IT        B   60000
2         HR        C   40000
3         HR        D   45000
4      Sales        E   70000
------------------------------
Department
HR       42500.0
IT       55000.0
Sales    70000.0
Name: Salary, dtype: float64
------------------------------
  Department Employee  Salary  Dept_Avg_Salary
0         IT        A   50000          55000.0
1         IT        B   60000          55000.0
2         HR        C   40000          42500.0
3         HR        D   45000          42500.0
4      Sales        E   70000          70000.0

In [12]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Sales", "Sales"],
    "Gender": ["M", "F", "M", "F", "M", "F"],
    "Salary": [50000, 60000, 40000, 45000, 70000, 65000]
})

print(df)
print('-' * 30)

#Average salary per dept
print(df.pivot_table(values = 'Salary',index = 'Department',aggfunc= 'mean'))
print('-' * 30)

# Avg salary per dept based on gender
print(df.pivot_table(values = 'Salary',columns='Gender',index = 'Department',aggfunc = 'mean'))
print('-' * 30)

# fill missing value
print(df.pivot_table(
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean",
    fill_value=0
))
print('-' * 30)

df.pivot_table(
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean",
    margins=True
)

  Department Gender  Salary
0         IT      M   50000
1         IT      F   60000
2         HR      M   40000
3         HR      F   45000
4      Sales      M   70000
5      Sales      F   65000
------------------------------
             Salary
Department
HR          42500.0
IT          55000.0
Sales       67500.0
------------------------------
Gender            F        M
Department
HR          45000.0  40000.0
IT          60000.0  50000.0
Sales       65000.0  70000.0
------------------------------
Gender            F        M
Department
HR          45000.0  40000.0
IT          60000.0  50000.0
Sales       65000.0  70000.0
------------------------------

Gender                 F             M      All
Department
HR          45000.000000  40000.000000  42500.0
IT          60000.000000  50000.000000  55000.0
Sales       65000.000000  70000.000000  67500.0
All         56666.666667  53333.333333  55000.0

In [18]:
# heatmap creation using gradient ,we can use seaborn or matplotlib library as well for this
import pandas as pd

df = pd.DataFrame({
    "Math": [90, 70, 80, 60],
    "Science": [85, 75, 65, 95],
    "English": [88, 72, 78, 85]
})

# higher -- darker , lower -- lighter , default is Blues
df.style.background_gradient(cmap = 'Greens')



# apply to specific col
df.style.background_gradient(subset=["Math","Science"],cmap = 'Reds')

In [21]:
# melt to convert wide table to long table
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B"],
    "Math": [90, 70],
    "Science": [85, 75],
    "English": [88, 72]
})

melted = df.melt(id_vars="Name")
print(melted)
print('-'* 30)

melt1 = df.melt(id_vars = 'Name',value_vars = ['Math','Science'],var_name = 'Subject',value_name='Score')
print(melt1)

  Name variable  value
0    A     Math     90
1    B     Math     70
2    A  Science     85
3    B  Science     75
4    A  English     88
5    B  English     72
------------------------------
  Name  Subject  Score
0    A     Math     90
1    B     Math     70
2    A  Science     85
3    B  Science     75